-- Création des tables

PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS PRESTATION;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS INDEPENDANT;

CREATE TABLE CLIENT (
    IDC INTEGER PRIMARY KEY AUTOINCREMENT,
    NOM TEXT,
    SIRET TEXT,
    VILLE TEXT,
    DOMAINE TEXT,
    TJM_ESTIME REAL,
    ADRESSE TEXT
);

CREATE TABLE INDEPENDANT (
    IDI INTEGER PRIMARY KEY AUTOINCREMENT,
    NOM TEXT,
    PRENOM TEXT,
    EMAIL TEXT,
    TELEPHONE TEXT
);

CREATE TABLE PRESTATION (
    IDP INTEGER PRIMARY KEY AUTOINCREMENT,
    IDC INTEGER NOT NULL,
    IDI INTEGER NOT NULL,
    INTITULE TEXT,
    DESCRIPTION TEXT,
    DATE_DEBUT TEXT,
    DATE_FIN TEXT,
    TJM_FINAL REAL,
    FOREIGN KEY (IDC) REFERENCES CLIENT(IDC),
    FOREIGN KEY (IDI) REFERENCES INDEPENDANT(IDI)
);

-- Données de départ

INSERT INTO CLIENT (NOM, SIRET, VILLE, DOMAINE, TJM_ESTIME, ADRESSE)
VALUES ('EntrepriseRandom', '12345678900000', 'Toulouse', 'Informatique', 500, '1 Rue Nomderue');

INSERT INTO INDEPENDANT (NOM, PRENOM, EMAIL, TELEPHONE)
VALUES ('Delance', 'Jeanne', 'jeanne.delance@mail.com', '0606060606');

INSERT INTO PRESTATION (IDC, IDI, INTITULE, DESCRIPTION, DATE_DEBUT, DATE_FIN, TJM_FINAL)
VALUES (1, 1, 'Développement API', 'Création d’une API en PHP', '2026-01-01', '2026-02-01', 500);